[package]
name = "repost"
version = "0.1.0"
authors = ["Miccah Castorina <m.castorina93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.23.1"
prettytable-rs = "0.8.0"
chrono = "0.4.11"
reqwest = { version = "0.10", features = ["blocking"] }
clap-v3 = "3.0.0-beta.1"
shlex = "0.1.1"
