[package]
name = "repost"
version = "0.1.0"
authors = ["Miccah Castorina <m.castorina93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.23.1"
chrono = "0.4.11"
reqwest = { version = "0.10", features = ["blocking"] }
clap-v3 = { version = "3.0.0-beta.1", features = ["yaml"] }
shlex = "0.1.1"
regex = "1"
colored = "1.9"
serde_json = "1.0"
comfy-table = "0.1.1"
terminal_size = "0.1.12"
rustyline = "6.2.0"
serde_yaml = "0.8"
